variables:
    CLI_VERSION: 12.2.0

build:
    stage: build
    image: trion/ng-cli
    before_script:
        - npm ci
    script:
        - ng build --prod
    artifacts:
        expire_in: 1 day
        paths:
            - dist/
    tags:
        - docker

test:karma:
    stage: test
    image: trion/ng-cli-karma
    before_script:
        - npm ci
    allow_failure: false
    script:
        - ng test  --code-coverage --progress false --watch false
    coverage: '/Lines \W+: (\d+\.\d+)%.*/'
    artifacts:
        paths:
            - coverage/
        reports:
            junit: [
                    reports/*.xml,
                    karma_html/index.html
            ]
    tags:
        - docker

test:nglint:
    stage: test
    image: trion/ng-cli:${CLI_VERSION}
    before_script:
        - npm ci
    allow_failure: false
    script:
        - ng lint
    tags:
        - docker

todo:e2e:
    stage: test
    image: trion/ng-cli:${CLI_VERSION}
    allow_failure: false
    script:
        - echo "Implement"
